class LanguagesInputSpeechList {
  static final _langs = {
    'af_ZA': 'afrikáans (Sudáfrica)',
    'ak_GH': 'akan (Ghana)',
    'sq_AL': 'albanés (Albania)',
    'de_DE': 'alemán (Alemania)',
    'de_AT': 'alemán (Austria)',
    'de_BE': 'alemán (Bélgica)',
    'de_CH': 'alemán (Suiza)',
    'am_ET': 'amárico (Etiopía)',
    'hy_AM': 'armenio (Armenia)',
    'az_AZ': 'azerbaiyano (Azerbaiyán)',
    'bn_BD': 'bengalí (Bangladés)',
    'bn_IN': 'bengalí (India)',
    'my_MM': 'birmano (Myanmar)',
    'bg_BG': 'búlgaro (Bulgaria)',
    'kn_IN': 'canarés (India)',
    'yue_HK': 'cantonés (han tradicional, Hong Kong)',
    'ca_ES': 'catalán (España)',
    'cs_CZ': 'checo (Chequia)',
    'si_LK': 'cingalés (Sri Lanka)',
    'cmn_CN': 'cmn (han simplificado, China)',
    'cmn_HK': 'cmn (han simplificado, Hong Kong)',
    'cmn_TW': 'cmn (han tradicional, Taiwán)',
    'ko_KR': 'coreano (Corea del Sur)',
    'hr_HR': 'croata (Croacia)',
    'da_DK': 'danés (Dinamarca)',
    'sk_SK': 'eslovaco (Eslovaquia)',
    'sl_SI': 'esloveno (Eslovenia)',
    'es_AR': 'español (Argentina)',
    'es_BO': 'español (Bolivia)',
    'es_CL': 'español (Chile)',
    'es_CO': 'español (Colombia)',
    'es_CR': 'español (Costa Rica)',
    'es_EC': 'español (Ecuador)',
    'es_SV': 'español (El Salvador)',
    'es_ES': 'español (España)',
    'es_US': 'español (Estados Unidos)',
    'es_GT': 'español (Guatemala)',
    'es_HN': 'español (Honduras)',
    'es_MX': 'español (México)',
    'es_NI': 'español (Nicaragua)',
    'es_PA': 'español (Panamá)',
    'es_PY': 'español (Paraguay)',
    'es_PE': 'español (Perú)',
    'es_PR': 'español (Puerto Rico)',
    'es_DO': 'español (República Dominicana)',
    'es_UY': 'español (Uruguay)',
    'es_VE': 'español (Venezuela)',
    'et_EE': 'estonio (Estonia)',
    'eu_ES': 'euskera (España)',
    'fil_PH': 'filipino (Filipinas)',
    'fi_FI': 'finés (Finlandia)',
    'fr_BE': 'francés (Bélgica)',
    'fr_CA': 'francés (Canadá)',
    'fr_FR': 'francés (Francia)',
    'fr_CH': 'francés (Suiza)',
    'gl_ES': 'gallego (España)',
    'ka_GE': 'georgiano (Georgia)',
    'el_GR': 'griego (Grecia)',
    'gu_IN': 'guyaratí (India)',
    'ha_GH': 'hausa (Ghana)',
    'ha_NG': 'hausa (Nigeria)',
    'iw_IL': 'hebreo (Israel)',
    'hi_IN': 'hindi (India)',
    'hu_HU': 'húngaro (Hungría)',
    'ig_NG': 'igbo (Nigeria)',
    'in_ID': 'indonesio (Indonesia)',
    'en_AU': 'inglés (Australia)',
    'en_CA': 'inglés (Canadá)',
    'en_US': 'inglés (Estados Unidos)',
    'en_PH': 'inglés (Filipinas)',
    'en_GH': 'inglés (Ghana)',
    'en_IN': 'inglés (India)',
    'en_ID': 'inglés (Indonesia)',
    'en_IE': 'inglés (Irlanda)',
    'en_KE': 'inglés (Kenia)',
    'en_001': 'inglés (Mundo)',
    'en_NG': 'inglés (Nigeria)',
    'en_NZ': 'inglés (Nueva Zelanda)',
    'en_GB': 'inglés (Reino Unido)',
    'en_SG': 'inglés (Singapur)',
    'en_ZA': 'inglés (Sudáfrica)',
    'en_TH': 'inglés (Tailandia)',
    'en_TZ': 'inglés (Tanzania)',
    'is_IS': 'islandés (Islandia)',
    'it_IT': 'italiano (Italia)',
    'it_CH': 'italiano (Suiza)',
    'ja_JP': 'japonés (Japón)',
    'jv_ID': 'javanés (Indonesia)',
    'km_KH': 'jemer (Camboya)',
    'kk_KZ': 'kazajo (Kazajistán)',
    'ki_KE': 'kikuyu (Kenia)',
    'rw_RW': 'kinyarwanda (Ruanda)',
    'rn_BI': 'kirundi (Burundi)',
    'lo_LA': 'lao (Laos)',
    'lv_LV': 'letón (Letonia)',
    'lt_LT': 'lituano (Lituania)',
    'mk_MK': 'macedonio (Macedonia del Norte)',
    'ml_IN': 'malayalam (India)',
    'ms_MY': 'malayo (Malasia)',
    'mr_IN': 'maratí (India)',
    'mn_MN': 'mongol (Mongolia)',
    'nr_ZA': 'ndebele meridional (Sudáfrica)',
    'nl_NL': 'neerlandés (Países Bajos)',
    'ne_NP': 'nepalí (Nepal)',
    'nb_NO': 'noruego bokmal (Noruega)',
    'ny_MW': 'nyanja (Malaui)',
    'ny_ZW': 'nyanja (latino, Zimbabue)',
    'om_ET': 'oromo (Etiopía)',
    'fa_IR': 'persa (Irán)',
    'pcm_NG': 'pidgin de Nigeria (Nigeria)',
    'pl_PL': 'polaco (Polonia)',
    'pt_BR': 'portugués (Brasil)',
    'pt_PT': 'portugués (Portugal)',
    'pa_IN': 'punyabí (gurmuji, India)',
    'ro_RO': 'rumano (Rumanía)',
    'ru_RU': 'ruso (Rusia)',
    'sr_RS': 'serbio (Serbia)',
    'tn_BW': 'setsuana (Botsuana)',
    'tn_ZA': 'setsuana (latino, Sudáfrica)',
    'sn_ZW': 'shona (Zimbabue)',
    'so_SO': 'somalí (Somalia)',
    'so_ET': 'somalí (latino, Etiopía)',
    'st_ZA': 'sotho meridional (Sudáfrica)',
    'st_LS': 'sotho meridional (latino, Lesoto)',
    'nso_ZA': 'sotho septentrional (Sudáfrica)',
    'sw_': 'suajili',
    'sw_TZ': 'suajili (Tanzania)',
    'ss_SZ': 'suazi (Esuatini)',
    'ss_ZA': 'suazi (latino, Sudáfrica)',
    'sv_SE': 'sueco (Suecia)',
    'su_ID': 'sundanés (Indonesia)',
    'th_TH': 'tailandés (Tailandia)',
    'ta_IN': 'tamil (India)',
    'ta_MY': 'tamil (Malasia)',
    'ta_SG': 'tamil (Singapur)',
    'ta_LK': 'tamil (Sri Lanka)',
    'te_IN': 'telugu (India)',
    'ti_ET': 'tigriña (Etiopía)',
    'ti_ER': 'tigriña (etiópico, Eritrea)',
    'ts_ZA': 'tsonga (Sudáfrica)',
    'tr_TR': 'turco (Turquía)',
    'uk_UA': 'ucraniano (Ucrania)',
    'ur_IN': 'urdu (India)',
    'ur_PK': 'urdu (Pakistán)',
    'uz_UZ': 'uzbeko (Uzbekistán)',
    've_ZA': 'venda (Sudáfrica)',
    'vi_VN': 'vietnamita (Vietnam)',
    'xh_ZA': 'xhosa (Sudáfrica)',
    'yo_BJ': 'yoruba (Benín)',
    'yo_NG': 'yoruba (Nigeria)',
    'zu_ZA': 'zulú (Sudáfrica)',
  };

  static String getLanguageName(String code) {
    return _langs[code] ?? 'Unknown language';
  }

  static List<String> getLanguageCodes() {
    return _langs.keys.toList();
  }

  static List<String> getLanguageNames() {
    return _langs.values.toList();
  }
}
